# Generated by Django 3.0.8 on 2020-07-16 08:58

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_movie_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
            preserve_default=False,
        ),
    ]
