# Generated by Django 3.0.8 on 2020-07-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_trailer',
        ),
    ]
