# Generated by Django 3.0.8 on 2020-07-18 07:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_remove_movie_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('action', 'ACTION'), ('biography', 'BIOGAPHY'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], max_length=37),
        ),
    ]
