# Generated by Django 3.0.8 on 2020-07-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_auto_20200718_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
