# Generated by Django 3.0.8 on 2020-07-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_auto_20200718_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='movie.movie')),
            ],
        ),
    ]
